apiVersion: v1
# <string>指定api资源版本,格式group/version
kind: ConfigMap
# <string>指定资源类别
metadata:
# <Object>指定元数据,内嵌字段
  name: pod-demo
  # <string>指定资源名称
  namespace: default
  # <string>指定名称空间,默认为default
  labels:
  # <map[string]string>指定标签格式为k:v,可以多个,每行一个
    app: myapp
  annotations:
  # 资源注解<map[string]string>,与label不同的地方在于,他不能用于选择资源对象,
  # 仅用于为对象提供"元数据"格式如下:
    jc.com/created-by: "cluster admin"
