#配置端口
server:
  port: 8081
  jsp-servlet:
    init-parameters:
      development: true
  #最外层的路径
#  context-path: /cas
spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tcc_account?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  aop:
    proxy-target-class: true
  redis:
    pool:
      max-idle: 10
      min-idle: 5
      max-wait: 2000
      max-active: 10
    timeout: 2000
  cache:
    cache-names: redisCache
    type: REDIS
    redis:
      time-to-live: 600000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: xlHost
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
mybatis:
  #配置mapper xml文件所在的路径
  mapper-locations: classpath:com.cas.dao.mapper/*.xml
  #Mybais 扫描别名包， 和注解@Alias联用
  type-aliases-package: com.cas.pojo
#  配置typeHandler 的扫描包
  typeHandler-handlers-package: com.cas.typeHandler
  configuration:
    map-underscore-to-camel-case: true
    interceptors: com.sso.util.interceptorceptor.MybatisInterceptor
# 日志配置
logging:
  config: classpath:logback-spring.xml






